# Generated by Django 5.1.5 on 2025-01-29 17:12

import config.models.base_model
import meme.models.meme
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meme", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="meme",
            managers=[
                ("objects", meme.models.meme.MemeModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="memecounter",
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
    ]
