version: '3.7'

services:
  dionysus:
    container_name: dionysus-webapp
    build:
        context: .
        dockerfile: ./environments/dev/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    volumes:
      - .:/app
      - ./environments/dev/start-webapp.sh:/start-webapp.sh
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - redis
    entrypoint:
      - /start-webapp.sh

  db:
    image: postgres:17
    expose:
      - "${POSTGRES_PORT}"
    ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: -p ${POSTGRES_PORT}

  db_test:
    image: postgres:17
    container_name: dionysus-test-db
    expose:
      - "5433"
    ports:
      - "5433:5433"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${TEST_POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    command: -p 5433

  redis:
    image: redis:7
    container_name: dionysus-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  celery-worker:
    container_name: dionysus-celery-worker
    build:
      context: .
      dockerfile: ./environments/dev/Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    command: celery -A config worker -l INFO

  celery-beat:
    container_name: dionysus-celery-beat
    build:
      context: .
      dockerfile: ./environments/dev/Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - celery-worker
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler

  flower:
    container_name: dionysus-flower
    build:
      context: .
      dockerfile: ./environments/dev/Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery-worker
    command: celery -A config flower --port=5555

volumes:
  postgres_data:
  postgres_test_data:
