version: '3.7'

services:
  dionysus:
    container_name: dionysus-webapp
    build:
        context: .
        dockerfile: ./environments/dev/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    volumes:
      - .:/app
      - ./environments/dev/start-webapp.sh:/start-webapp.sh
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    entrypoint:
      - /start-webapp.sh
  db:
    image: postgres:17
    expose:
      - "${POSTGRES_PORT}"
    ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - ./environments/dev/db_initial_setup.sql:/docker-entrypoint-initdb.d/initial_setup.sql
      - postgres_data:/var/lib/postgresql/data/
    command: -p ${POSTGRES_PORT}
volumes:
    postgres_data: