# Generated by Django 5.1.5 on 2025-01-29 17:18

import config.models.base_model_with_soft_delete
import tag.models.tag
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="memetagging",
            managers=[
                (
                    "objects",
                    config.models.base_model_with_soft_delete.SoftDeleteManager(),
                ),
            ],
        ),
        migrations.AlterModelManagers(
            name="tag",
            managers=[
                ("objects", tag.models.tag.TagModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="tagcategory",
            managers=[
                (
                    "objects",
                    config.models.base_model_with_soft_delete.SoftDeleteManager(),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tag",
            name="first_letter",
            field=models.CharField(db_index=True, default="", max_length=1),
        ),
        migrations.AddField(
            model_name="tag",
            name="split_name",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
