# Generated by Django 5.1.5 on 2025-01-29 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTagCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bookmarks_count", models.PositiveIntegerField(default=0)),
                ("bookmarkings_count", models.PositiveIntegerField(default=0)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_counters",
                        to="tag.tag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_counters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user_tag_counter",
                "verbose_name_plural": "user_tag_counters",
                "db_table": "user_tag_counters",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "tag"), name="unique_user_tag_counter"
                    )
                ],
            },
        ),
    ]
