# Generated by Django 5.1.5 on 2025-01-29 17:12

import config.models.base_model
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_usertagcounter"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usertagcounter",
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
    ]
