# Generated by Django 5.1.5 on 2025-01-29 17:12

import config.models.base_model
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0003_bookmarking_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="bookmark",
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="bookmarking",
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
    ]
