# Generated by Django 5.1.7 on 2025-09-09 17:33

import config.models.base_model
import django.db.models.deletion
import studio.models.canvas
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("image", models.ImageField(upload_to="stickers/")),
                ("description", models.TextField(blank=True, null=True)),
                ("active_at", models.DateTimeField(blank=True, null=True)),
                ("inactive_at", models.DateTimeField(blank=True, null=True)),
                ("ticket_price", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Sticker",
                "verbose_name_plural": "Stickers",
                "db_table": "studio_stickers",
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
        migrations.CreateModel(
            name="Canvas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("background_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("content", models.JSONField(default=list)),
                ("is_public", models.BooleanField(default=False)),
                ("is_template", models.BooleanField(default=False)),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="canvas_previews/"
                    ),
                ),
                (
                    "complete_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="canvas_completes/"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "using_stickers",
                    models.ManyToManyField(
                        related_name="canvases", to="studio.sticker"
                    ),
                ),
            ],
            options={
                "verbose_name": "Canvas",
                "verbose_name_plural": "Canvases",
                "db_table": "studio_canvases",
            },
            managers=[
                ("objects", studio.models.canvas.CanvasManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_ticket",
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Ticket",
                "verbose_name_plural": "User Tickets",
                "db_table": "studio_user_tickets",
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserTicketHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("buy_sticker", "Buy Sticker"),
                            ("use_template", "Use Template"),
                            ("earn_from_sticker_share", "Earn from Sticker Share"),
                            ("earn_from_template_share", "Earn from Template Share"),
                            ("admin_adjustment", "Admin Adjustment"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "canvas",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="studio.canvas",
                    ),
                ),
                (
                    "sticker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="studio.sticker",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Ticket History",
                "verbose_name_plural": "User Ticket Histories",
                "db_table": "studio_user_ticket_histories",
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserSticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="studio.sticker"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Sticker",
                "verbose_name_plural": "User Stickers",
                "db_table": "studio_user_stickers",
                "unique_together": {("user", "sticker")},
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
    ]
