# Generated by Django 5.1.7 on 2025-09-10 06:09

import django.db.models.deletion
import studio.models.sticker
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="sticker",
            managers=[
                ("objects", studio.models.sticker.StickerManager()),
            ],
        ),
        migrations.AddField(
            model_name="sticker",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
