# Generated by Django 5.1.5 on 2025-01-29 17:12

import config.models.base_model_with_soft_delete
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="audio",
            managers=[
                (
                    "objects",
                    config.models.base_model_with_soft_delete.SoftDeleteManager(),
                ),
            ],
        ),
        migrations.AlterModelManagers(
            name="thumbnail",
            managers=[
                (
                    "objects",
                    config.models.base_model_with_soft_delete.SoftDeleteManager(),
                ),
            ],
        ),
        migrations.AlterModelManagers(
            name="video",
            managers=[
                (
                    "objects",
                    config.models.base_model_with_soft_delete.SoftDeleteManager(),
                ),
            ],
        ),
    ]
